### ISSUE TITLE
adaptors and schemas for classic ontologies

### ISSUE THREAD

**Issue by hitz** [saezlab/BioCypher#100]
hey we are testing out biocypher to create a KG for the IGVF (impact of genomic variation on function) Catalog.

As a baseline we were going to load a few (6?) base OWL ontologies into biolink schema... Do you have a generic adaptor for OWL/OBO files?

**Comment by slobentanzer** [comment]
Hi @hitz,
thanks for the question, it's great you're trying it out! :)

We do indeed have a generic way of dealing with OBO files, in the `OntologyAdapter` class that is generated by the `Driver`.  Currently, I have been using it to fuse only one ontology to the Biolink backbone (see for instance the OncodashKB stub [here](https://github.com/oncodash/oncodashkb) or the test `test_generic_ontology_adapter` in `test_translate.py`.

However, adding multiple ontologies onto the Biolink backbone is functionality that is planned but not implemented yet, so it would be great to use your use case as an opportunity to do this implementation. I estimate it should be relatively fast to implement going from what we currently have, by simply passing in an array of "tail ontology" files and fusing points. Do you want to write me an email at sebastian.lobentanzer@uni-heidelberg.de, so that we could talk about the details?

**Comment by slobentanzer** [comment]
I am tying this issue to the implementation of an extended generic ontology adapter (#107), able to deal with multiple input ontologies.

**Comment by slobentanzer** [comment]
Closing because #107 was addressed.
